### ISSUE TITLE
how to withdraw?

### ISSUE THREAD

**Issue by ntn888** [lgcarrier/xrppaperwallet#1]
Hi I made a cold wallet using this application and transferred funds into it (yes above the minimum 20xrp amount). I can see successful transfer in the xrp ledger..

Now I want to withdraw from this cold wallet.. I try to use `https://jatchili.github.io/minimalist-ripple-client/` but it says `not a valid secret` when I put in my secret key there.

What is the method to withdraw the funds? Thank you.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by ntn888** [comment]
Okay, need to use the xaman mobile wallet to access it. All good!

**Comment by Fonseca624** [comment]
Hello @ntn888  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by lgcarrier** [comment]
Correct, Xaman is a good wallet: https://xaman.app/
